import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const rootDirectory = path.resolve(scriptDirectory, "..");
const dataPath = path.join(rootDirectory, "data", "projects.js");
const errors = [];
const context = { window: {} };

vm.runInNewContext(fs.readFileSync(dataPath, "utf8"), context, { filename: dataPath });
const projects = context.window.PORTFOLIO_PROJECTS;
const requiredFields = ["id", "title", "role", "timeline", "status", "category", "problem", "outcome", "summary"];
const publishedProjects = Array.isArray(projects) ? projects.filter((project) => project.published === true) : [];

if (!Array.isArray(projects) || !projects.length) {
  errors.push("No projects were found in data/projects.js.");
} else {
  const ids = new Set();

  for (const project of projects) {
    if (typeof project.published !== "boolean") errors.push(`${project.id || "Unknown project"}: published must be true or false.`);
    for (const field of requiredFields) {
      if (!project[field]) errors.push(`${project.id || "Unknown project"}: missing ${field}.`);
    }

    if (ids.has(project.id)) errors.push(`Duplicate project id: ${project.id}.`);
    ids.add(project.id);

    const routePath = path.join(rootDirectory, "projects", project.id, "index.html");
    if (project.published) {
      if (!fs.existsSync(routePath)) {
        errors.push(`${project.id}: generated route is missing. Run npm run build.`);
      } else if (!fs.readFileSync(routePath, "utf8").includes(`data-project-id="${project.id}"`)) {
        errors.push(`${project.id}: generated route contains the wrong project id.`);
      }
    } else if (fs.existsSync(routePath) && fs.readFileSync(routePath, "utf8").includes("Generated by scripts/build-project-pages.mjs")) {
      errors.push(`${project.id}: unpublished project still has a generated route. Run npm run build.`);
    }

    const mediaItems = [project.image, ...(project.gallery || [])];
    for (const item of mediaItems) {
      const source = typeof item === "string" ? item : item?.src;
      if (!source || /^(?:[a-z]+:|\/\/)/i.test(source)) continue;
      if (!fs.existsSync(path.join(rootDirectory, source))) errors.push(`${project.id}: missing media file ${source}.`);
    }
  }
}

const requiredPages = ["index.html", "project.html", "projects/index.html", "404.html", "robots.txt", "sitemap.xml", "CNAME"];
for (const page of requiredPages) {
  if (!fs.existsSync(path.join(rootDirectory, page))) errors.push(`Missing required site file: ${page}.`);
}

const htmlFiles = [
  "index.html",
  "project.html",
  "projects/index.html",
  "404.html",
  "about.html",
  "resume.html",
  "contact.html",
  "work.html",
  ...publishedProjects.map((project) => `projects/${project.id}/index.html`)
];

for (const relativeFile of htmlFiles) {
  const filePath = path.join(rootDirectory, relativeFile);
  if (!fs.existsSync(filePath)) continue;
  const html = fs.readFileSync(filePath, "utf8");
  const ids = [...html.matchAll(/\sid="([^"]+)"/g)].map((match) => match[1]);
  const duplicateIds = ids.filter((id, index) => ids.indexOf(id) !== index);
  if (duplicateIds.length) errors.push(`${relativeFile}: duplicate ids ${[...new Set(duplicateIds)].join(", ")}.`);

  for (const match of html.matchAll(/\s(?:href|src)="([^"]+)"/g)) {
    const reference = match[1];
    if (!reference || /^(?:[a-z]+:|#|\/\/)/i.test(reference)) continue;
    const cleanReference = reference.split(/[?#]/)[0];
    if (!cleanReference) continue;
    let target = reference.startsWith("/")
      ? path.join(rootDirectory, cleanReference.slice(1))
      : path.resolve(path.dirname(filePath), cleanReference);
    if (cleanReference.endsWith("/")) target = path.join(target, "index.html");
    if (!fs.existsSync(target)) errors.push(`${relativeFile}: broken local reference ${reference}.`);
  }
}

if (errors.length) {
  console.error(errors.map((error) => `- ${error}`).join("\n"));
  process.exitCode = 1;
} else {
  console.log(`Site check passed: ${publishedProjects.length} published projects, ${htmlFiles.length} HTML pages, and all referenced media found.`);
}
